services:
  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "${TIKA_PORT-9998}:9998"
    configs:
      - source: tika_config_3
        target: /tika-config.xml
    restart: unless-stopped
    
configs:
  tika_config_3:
    file: ./tika-config.xml